dbt_project:
  outputs:
    dev:
      account: ********
      database: AIRBNB
      password: ***********
      role: ACCOUNTADMIN
      schema: DBT_Schema
      threads: 1
      type: snowflake
      user: KARANBHATT081
      warehouse: COMPUTE_WH
  target: dev
